BASE_PAGE_TITLE = "CSR Action Guide"

SPECIAL_HANDLING = "Recommendation for Additional Imaging - Special Handling/Complex"
ADDITIONAL_IMAGING = "Unmapped Recommendation"
INTERVENTIONAL_PROCEDURE = "Interventional Procedure Recommendation"
NON_RADIOLOGY = "Non-Radiology Recommendation"
LATERALITY_UNSPECIFIED = (
    "Recommendation for Additional Imaging - Laterality Unspecified"
)

SPECIAL_RECOMMENDABLES = {
    ADDITIONAL_IMAGING: """**Unmapped modality/body part pair**: Additional imaging is 
    being recommended, but the no pre-defined
    recommendation exists for this combination of body part, modality, and laterality. The
    recommendation will be routed to the Radiology Safety Net for ordering based on the 
    text in the report itself, who may contact the recommending radiologist for clarification.""",
    INTERVENTIONAL_PROCEDURE: """An interventional procedure is being recommended (either
    within radiology or another department). The recommendation will be routed to the 
    Ambulatory Safety Net for management based on the text in the report itself. They may
    contact the recommending radiologist for additional information.""",
    NON_RADIOLOGY: """A non-radiology recommendation is being made. The recommendation will be
    routed to the Ambulatory Safety Net for management based on the text in the report itself.
    They may contact the recommending radiologist for additional information.""",
    LATERALITY_UNSPECIFIED: """A recommendation for additional imaging is being made, but the
    specified exam requires more information on laterality to permit ordering. The recommendation
    will be routed to the Radiology Safety Net for management based on the text in the report, 
    who may contact the recommending radiologist for clarification.""",
    SPECIAL_HANDLING: """A recommendation for additional imaging is being made, but the specified
    exam requires special handling beyond what should be handled by an automated system. The
    recommendation will be routed to the Radiology Safety Net for management based on the text
    in the report, who may contact the recommending radiologist for clarification.""",
}

FILE_NAMES = {
    "mappings": "./data/body_part_modality_laterality_recommendable.parquet",
    "report_codes": "./data/report_codes.parquet",
    "recommendables": "./data/recommendables.parquet",
    "modality_mappings": "./data/modality_mappings.parquet",
}

BODY_PART_OPTIONS = [
    "",
    "Abdomen & Pelvis",
    "· Abdomen",
    "· · Abdominal Vessels",
    "· · · Adrenal Vessels",
    "· · · Hepatic Vessels",
    "· · · Renal Vessels",
    "· · Adrenal",
    "· · Bile Ducts",
    "· · Biliary Tract",
    "· · Gallbladder",
    "· · IVC",
    "· · Kidney",
    "· · Liver",
    "· · Pancreas",
    "· · Peritoneum",
    "· · Portal Circulation",
    "· · Renal",
    "· · Spleen",
    "· · Stomach",
    "· Abdominal & Pelvic Arteries",
    "· · Abd/Pelv 1st Order Arteries",
    "· · Abd/Pelv 2nd Order Arteries",
    "· · Abd/Pelv 3rd Order Arteries",
    "· · Abd/Pelv Additional Arteries",
    "· · Abdominal Aorta",
    "· · Pelvic Arteries",
    "· · Visceral Arteries",
    "· Bladder",
    "· Colon",
    "· Pelvis",
    "· · Fallopian Tube",
    "· · Female Genital Tract",
    "· · · Uterus",
    "· · · Vagina",
    "· · Male Genital Tract",
    "· · Pelvic Vessels",
    "· · Pelvis - Lymph Node",
    "· · Prostate",
    "· · Sacrum",
    "· Rectum",
    "· Retroperitoneum",
    "· Small Intestine",
    "· Upper GI Tract",
    "· Urinary Tract",
    "Breast",
    "Cardiac",
    "· Coronary Arteries",
    "· Heart",
    "Chest",
    "·  Airway",
    "·  Bronchial Tree",
    "·  Chest - Lymph Node",
    "·  Chest Wall",
    "·  Lungs",
    "·  Pleura",
    "·  Ribs",
    "·  SVC",
    "·  Thoracic Arteries",
    "· ·  Internal Mammary Artery",
    "· ·  Pulmonary Arteries",
    "· ·  Thoracic 1st Order Arteries",
    "· ·  Thoracic 2nd Order Arteries",
    "· ·  Thoracic 3rd Order Arteries",
    "· ·  Thoracic Additional Arteries",
    "· ·  Thoracic Aorta",
    "·  Thoracic Esophagus",
    "·  Thoracic Vessels",
    "External Genitalia",
    "·  Penis",
    "·  Testis",
    "Extremity",
    "·  Lower Extremity",
    "· ·  Ankle",
    "· ·  Foot",
    "· ·  Hip",
    "· ·  Knee",
    "· ·  Leg",
    "· ·  Lower Extremity Arteries",
    "· · ·  Leg Arteries",
    "· · ·  Lower Extr. 1st Order Arteries",
    "· · ·  Lower Extr. 2nd Order Arteries",
    "· · ·  Lower Extr. 3rd Order Arteries",
    "· · ·  Lower Extr. Additional Arteries",
    "· ·  Lower Extremity Joint",
    "· ·  Lower Extremity Vessels",
    "· ·  Lymphatics",
    "· ·  Thigh",
    "·  Upper Extremity",
    "· ·  Arm",
    "· ·  Elbow",
    "· ·  Fingers",
    "· ·  Forearm",
    "· ·  Hand",
    "· ·  Shoulder",
    "· ·  Upper Extremity Arteries",
    "· · ·  Brachial Artery",
    "· · ·  Upper Extr. 1st Order Arteries",
    "· · ·  Upper Extr. 2nd Order Arteries",
    "· · ·  Upper Extr. 3rd Order Arteries",
    "· · ·  Upper Extr. Additional Arteries",
    "· ·  Upper Extremity Joint",
    "· ·  Upper Extremity Vessels",
    "· ·  Wrist",
    "Head & Neck",
    "·  Head",
    "· ·  Brain",
    "· ·  Dental",
    "· ·  Ear",
    "· ·  Internal Auditory Meatus",
    "· ·  Intracranial Vessels",
    "· ·  Mastoids",
    "· ·  Nasolacrimal Duct",
    "· ·  Orbit Vessels",
    "· ·  Orbits",
    "· ·  Posterior Fossa",
    "· ·  Salivary Glands",
    "· ·  Skull",
    "· ·  Temporomandibular Joint",
    "·  Max-Face",
    "· ·  Face",
    "· ·  Facial bones",
    "· ·  Mandible",
    "· ·  Nasal Bones",
    "· ·  Paranasal Sinuses",
    "·  Neck",
    "· ·  Cervical Esophagus",
    "· ·  Extracranial Vessels",
    "· ·  Larynx",
    "· ·  Neck - Lymph Node",
    "· ·  Neck Arteries",
    "· · ·  Carotid Arteries",
    "· · ·  External Carotid Arteries",
    "· · ·  Neck 1st Order Arteries",
    "· · ·  Neck 2nd Order Arteries",
    "· · ·  Neck 3rd Order Arteries",
    "· · ·  Neck Additional Arteries",
    "· · ·  Vertebral Arteries",
    "· ·  Parathyroid",
    "· ·  Pharynx",
    "· ·  Thyroid",
    "Other",
    "·  Veins",
    "· ·  Ovarian Vein",
    "· ·  Systemic Veins",
    "·  Vessels",
    "· ·  Additional Vessels",
    "· ·  Initial Vessel",
    "· ·  Systemic Vessels",
    "Spine",
    "·  Celiac Plexus",
    "·  Cervical Spine",
    "·  Coccyx",
    "·  Lumbar Spine",
    "·  Sacral Spine",
    "·  Sacroiliac Joints",
    "·  Thoracic Spine",
    "Unspecified Body Region",
    "Whole Body",
    "·  Bone",
    "· ·  Appendicular Skeleton",
]

MODALITY_OPTIONS = [
    "",
    "Absorptiometry",
    "·  DEXA",
    "·  X-Ray - Absorptiometry",
    "Consult",
    "Conventional Tomography",
    "CT",
    "·  Calcium Scoring",
    "·  CTA",
    "Echocardiography",
    "EEG",
    "ETT",
    "Fluoroscopy",
    "·  Fluoroscopy - Dynamic",
    "Invasive",
    "·  Angiography",
    "·  Angioplasty",
    "·  Arterial Procedure",
    "·  Arthrography",
    "·  Atherectomy",
    "·  Bronchography",
    "·  Cardiac Procedure",
    "·  Catheter Drainage",
    "·  Catheter Infusion",
    "·  Catheterization Cardiac",
    "·  Catheterization Transcervical",
    "·  Cholangiography",
    "·  Cisternography",
    "·  CT - Guided Biopsy",
    "·  Dacryocystography",
    "·  Diskography",
    "·  Endoscopic Procedure",
    "·  Epidurography",
    "·  Fistulogram",
    "·  Fluoroscopy Guidance",
    "·  GI Procedure",
    "·  GU Procedure",
    "·  Gyn Procedure",
    "·  Image Guided Biopsy",
    "·  Laryngography",
    "·  Lymphangiography",
    "·  Mammography Procedure",
    "·  MRI - Guided Biopsy",
    "·  Myelography",
    "·  OB Procedure",
    "·  Obstetrical",
    "·  Pacer Insertion",
    "·  Peritoneogram",
    "·  Sialography",
    "·  Sinogram",
    "·  Spinal Procedure",
    "·  Splenoportography",
    "·  Stent Placement",
    "·  Thrombectomy",
    "·  Thrombolysis",
    "·  Transcatheter Therapy",
    "·  US - IVUS",
    "·  US Procedure",
    "·  Vascular Procedure",
    "·  Venography",
    "·  Vertebroblasty",
    "Mammography",
    "·  Ductogram",
    "MEG",
    "MR",
    "·  MRA",
    "·  MRI",
    "·  MRI - Flow Mapping",
    "·  MRI - Functional",
    "·  Spectroscopy",
    "Nuclear Medicine",
    "·  Gamma Camera Imaging - Planar",
    "·  NUC- Spect",
    "·  NUC- Venography",
    "·  Urea Breath Test",
    "Panographic Radiography",
    "PET",
    "·  PET - Perfusion",
    "·  PET w/ CT",
    "Post Processing",
    "·  3D Render",
    "Radiography",
    "·  Cephalogram",
    "·  Cholecystography",
    "·  Pelvimetry",
    "·  X-Ray - Dental",
    "·  X-Ray - Diskography",
    "·  X-Ray- Magnification",
    "·  X-Ray- Specimen",
    "·  X-Ray - Standard",
    "·  X-Ray - Stereoscopic",
    "·  X-Ray w/ Fluoroscopy",
    "Unspecified Radiology Procedure",
    "US",
    "·  Sonohysterography",
    "·  US - Duplex",
    "·  US - Obstetrical",
    "·  US - Ophthalmic",
    "·  US - Transcranial",
    "·  US - Transesophageal",
    "·  US - Transrectal",
    "·  Vascular Lab",
]
